# change to your project with compute time available
project: e14
queue: normal
walltime: 00:59:00
jobname: mom6_isomip
ncpus: 48
jobfs: 10GB

# change to a project you have access to
# shortpath: x77

model: mom6
input:
    - /home/552/pc5520/ISOMIP/
exe: /home/552/pc5520/mom6-ninja-nci/ocean_only_symmetric/MOM6

collate: false
runlog: true
storage:
  gdata:
    - ik11

platform:
  nodesize: 48

mpi:
  module: openmpi/4.1.2
